"""
PDF Report Generator
"""
import os
from datetime import datetime
from typing import Dict
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors

def generate_report(contract_id: str, analysis_data: Dict) -> str:
    """
    Generate PDF report for contract analysis
    
    Args:
        contract_id: Contract identifier
        analysis_data: Analysis results
        
    Returns:
        Path to generated PDF file
    """
    # Create reports directory
    report_dir = 'data/reports'
    os.makedirs(report_dir, exist_ok=True)
    
    # Generate filename
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"contract_analysis_{contract_id}_{timestamp}.pdf"
    filepath = os.path.join(report_dir, filename)
    
    # Create PDF
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1a1a1a'),
        spaceAfter=30
    )
    story.append(Paragraph("Contract Analysis Report", title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Contract Info
    contract_type = analysis_data.get('contract_type', 'Unknown')
    risk_score = analysis_data.get('risk_score', 0)
    risk_level = analysis_data.get('risk_level', 'unknown')
    
    story.append(Paragraph(f"<b>Contract ID:</b> {contract_id}", styles['Normal']))
    story.append(Paragraph(f"<b>Contract Type:</b> {contract_type.title()}", styles['Normal']))
    story.append(Paragraph(f"<b>Risk Score:</b> {risk_score}/100", styles['Normal']))
    story.append(Paragraph(f"<b>Risk Level:</b> {risk_level.upper()}", styles['Normal']))
    story.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Summary
    story.append(Paragraph("<b>Executive Summary</b>", styles['Heading2']))
    summary = analysis_data.get('summary', 'No summary available')
    story.append(Paragraph(summary, styles['Normal']))
    story.append(Spacer(1, 0.2*inch))
    
    # Risk Flags
    risk_flags = analysis_data.get('risk_flags', [])
    if risk_flags:
        story.append(Paragraph("<b>Risk Flags</b>", styles['Heading2']))
        for flag in risk_flags[:10]:  # Top 10 risks
            flag_text = f"• {flag.get('type', 'Unknown')}: {flag.get('description', '')}"
            story.append(Paragraph(flag_text, styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
    
    # Recommendations
    recommendations = analysis_data.get('recommendations', [])
    if recommendations:
        story.append(Paragraph("<b>Recommendations</b>", styles['Heading2']))
        for i, rec in enumerate(recommendations, 1):
            story.append(Paragraph(f"{i}. {rec}", styles['Normal']))
        story.append(Spacer(1, 0.2*inch))
    
    # Clause Summary Table
    clauses = analysis_data.get('clauses', [])
    if clauses:
        story.append(Paragraph("<b>Clause Analysis</b>", styles['Heading2']))
        
        table_data = [['#', 'Risk Level', 'Type', 'Preview']]
        for i, clause in enumerate(clauses[:15], 1):  # First 15 clauses
            preview = clause.get('text', '')[:80] + '...'
            table_data.append([
                str(i),
                clause.get('risk_level', 'unknown'),
                clause.get('type', 'general'),
                preview
            ])
        
        table = Table(table_data, colWidths=[0.5*inch, 1*inch, 1*inch, 4*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(table)
    
    # Disclaimer
    story.append(Spacer(1, 0.5*inch))
    disclaimer = """<i>Disclaimer: This analysis is generated by AI and should not be considered legal advice. 
    Please consult with a qualified legal professional before making any decisions based on this report.</i>"""
    story.append(Paragraph(disclaimer, styles['Normal']))
    
    # Build PDF
    doc.build(story)
    
    return filepath
